### ISSUE TITLE
compiling with lwip

### ISSUE THREAD

**Issue by rav1ne** [russdill/tunsocks#2]
Hello,

sorry i've found no instructions on compiling. Which lwip version do i need? I've tried with 2, 1.4.0, 1.4.1... all throws error.
Currently i'm using ocproxy, but i have issues with it. I need to restart openconnect every 2-3 days, but i'm not sure it's an OC or proxy issue, so i would like to check this.

Thanks!

**Comment by rav1ne** [comment]
Ok, using ocproxy's lwip folder it went through,  installed libevent, but now it's looking for snmp_mib2.h which  seems to be part of the lwip 2.x branch, so i'm stuck again.

**Comment by sssemil** [comment]
Try using this lwip `git://git.savannah.gnu.org/lwip.git` and don't forget to install `libevent-dev`.

**Comment by rav1ne** [comment]
Nah, it's beyond me.
I guess the official git is here:
git clone https://git.savannah.nongnu.org/lwip.git

But it's seems the same 2.x tree. 
Ocproxy links to the lwip-contrib also, which has the neccessary headers i miss from the core lwip. At least i guess this is why the compilation fails.

**Comment by rav1ne** [comment]
For the record, the error i get:
`In file included from lwip/src/api/err.c:41:0:
./lwip/src/include/lwip/sys.h:393:1: error: unknown type name ‘sys_prot_t’
 sys_prot_t sys_arch_protect(void);
 ^
./lwip/src/include/lwip/sys.h:394:25: error: unknown type name ‘sys_prot_t’
 void sys_arch_unprotect(sys_prot_t pval);
                         ^
Makefile:531: recipe for target 'lwip/src/api/err.o' failed
make: *** [lwip/src/api/err.o] Error 1
`

**Comment by Pennix** [comment]
Hi
I just succeeded compiling tunsocks. 

clone lwip from official repository
`git clone https://git.savannah.nongnu.org/git/lwip.git`

checkout commit "58895c3"
`cd lwip;
git checkout 58895c3`

copy lwip into tunsocks directory and compile :)

**Comment by rav1ne** [comment]
Thanks, that worked!

However, i can't get it to work with openconnect. This should be ocproxy-compatible, right?
