### ISSUE TITLE
Can it forward all udp traffic to socks5 proxy?

### ISSUE THREAD

**Issue by GreatFireWall** [russdill/tunsocks#4]
as title.

**Comment by russdill** [comment]
It is a SOCKS5 proxy. It forwards raw packets IP (including UDP and TCP) over a pipe or tun device. I'm not sure what you are asking.  It does now have support for UDP requests from SOCKS5 clients.

**Comment by GreatFireWall** [comment]
sorry, I means can it capture all traffic (including tcp & udp) through the network adapter and forward to my proxy ?
I want to using for proxy some programs that do not support socks5 proxy or any others proxy.

**Comment by russdill** [comment]
tunsocks does the exact opposite of what you want. tunsocks provides a normal socks server, but sends raw ip packets upstream. You want to capture raw IP packets and act like a normal socks server upstream. This can be accomplished with a transparent socks proxy, like redsocks:

http://darkk.net.ru/redsocks/
