### ISSUE TITLE
Error getting/compiling tunsocks

### ISSUE THREAD

**Issue by msedv** [russdill/tunsocks#8]
Hi,

the reference to lwip-udhcpd isn't valid anymore:

git submodule update --init
...
Submodul-Pfad: 'lwip-nat': 'ea92f638429818eb4aa034336adb01200cdf50e2' ausgecheckt
error: no such remote ref f85de3a623dafc02bfe3aa963d21c5a4c8bbb251
"fetch" in Submodul-Pfad 'lwip-udhcpd' ausgeführt, aber f85de3a623dafc02bfe3aa963d21c5a4c8bbb251 nicht
enthalten. Direktes Anfordern dieses Commits ist fehlgeschlagen.

**Comment by russdill** [comment]
Sorry, pushed.
